// Objective-C API for talking to gomobile-download-upload/gonet Go package.
//   gobind -lang=objc gomobile-download-upload/gonet
//
// File is generated by gobind. Do not edit.

#ifndef __Gonet_H__
#define __Gonet_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class GonetBlock;
@class GonetDirDownloader;
@class GonetDownloadManager;
@class GonetDownloadWaitChanStruct;
@class GonetFileDirDownloadTask;
@class GonetFileDownloadInfo;
@class GonetFileDownloadTask;
@class GonetFileDownloader;
@class GonetFileUploadInfo;
@class GonetFileUploader;
@class GonetResourceList;
@class GonetResourcesResp;
@class GonetTask;
@class GonetUploadManager;
@class GonetUploadTask;
@class GonetUploadWaitChanStruct;
@protocol GonetCallback;
@class GonetCallback;
@protocol GonetDownloadCallBack;
@class GonetDownloadCallBack;
@protocol GonetUploadCallBack;
@class GonetUploadCallBack;
@protocol GonetWorker;
@class GonetWorker;

@protocol GonetCallback <NSObject>
- (void)sendResult:(NSString* _Nullable)json;
@end

@protocol GonetDownloadCallBack <NSObject>
- (void)onFinish:(NSString* _Nullable)p0;
- (void)onStart:(NSString* _Nullable)p0;
- (void)sendDownloadResult:(NSString* _Nullable)p0;
@end

@protocol GonetUploadCallBack <NSObject>
- (void)onFinish:(NSString* _Nullable)p0;
- (void)onStart:(NSString* _Nullable)p0;
- (void)sendUploadResult:(NSString* _Nullable)p0;
@end

@protocol GonetWorker <NSObject>
- (void)onDelete;
- (void)onFail;
- (void)onFinish;
- (void)onPause;
- (void)onQuit;
// skipped method Worker.OnStart with unsupported parameter or return types

@end

/**
 * Block 块
 */
@interface GonetBlock : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) int64_t begin;
@property (nonatomic) int64_t end;
@end

@interface GonetDirDownloader : NSObject <goSeqRefInterface, GonetWorker> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(NSString* _Nullable)findApi downloadApi:(NSString* _Nullable)downloadApi downloadPath:(NSString* _Nullable)downloadPath path:(NSString* _Nullable)path headerStr:(NSString* _Nullable)headerStr pwd:(NSString* _Nullable)pwd userId:(long)userId areaId:(long)areaId;
@property (nonatomic) GonetFileDownloadInfo* _Nullable fileDownloadInfo;
// skipped field DirDownloader.FileDownloads with unsupported type: []*gomobile-download-upload/gonet.FileDownloader

@property (nonatomic) NSString* _Nonnull path;
/**
 * OnDelete 删除
 */
- (void)onDelete;
/**
 * OnFail 失败事件
 */
- (void)onFail;
/**
 * OnFinish 任务完成时触发的事件
 */
- (void)onFinish;
/**
 * OnPause 暂停下载
 */
- (void)onPause;
/**
 * OnQuit 退出App事件
 */
- (void)onQuit;
// skipped method DirDownloader.OnStart with unsupported parameter or return types

// skipped method DirDownloader.Run with unsupported parameter or return types

@end

@interface GonetDownloadManager : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(NSString* _Nullable)host dbPath:(NSString* _Nullable)dbPath headerStr:(NSString* _Nullable)headerStr;
// skipped field DownloadManager.Workers with unsupported type: map[int]gomobile-download-upload/gonet.Worker

// skipped field DownloadManager.Cancels with unsupported type: map[int]context.CancelFunc

@property (nonatomic) NSString* _Nonnull host;
@property (nonatomic) NSString* _Nonnull dbPath;
@property (nonatomic) NSString* _Nonnull headerStr;
- (void)changeHost:(NSString* _Nullable)host;
/**
 * CreateDirDownloader 创建文件夹下载对象
 */
- (void)createDirDownloader:(NSString* _Nullable)findApi downloadApi:(NSString* _Nullable)downloadApi downloadPath:(NSString* _Nullable)downloadPath headerStr:(NSString* _Nullable)headerStr pwd:(NSString* _Nullable)pwd userId:(long)userId areaId:(long)areaId;
/**
 * CreateFileDownloader 创建文件下载对象
 */
- (void)createFileDownloader:(NSString* _Nullable)url headerStr:(NSString* _Nullable)headerStr pwd:(NSString* _Nullable)pwd userId:(long)userId areaId:(long)areaId;
- (void)delete:(long)id_;
/**
 * NetworkNil 网速设置为0，全部设置失败
 */
- (void)networkNil;
- (void)quitAPP;
/**
 * Run 开始下载任务，只能有2个任务
 */
- (void)run:(NSString* _Nullable)headerStr;
/**
 * Start 启动某个项目
 */
- (void)start:(long)id_;
/**
 * Stop 暂停某个项目
 */
- (void)stop:(long)id_;
@end

/**
 * DownloadWaitChanStruct 下载任务结构体
 */
@interface GonetDownloadWaitChanStruct : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long id_;
@property (nonatomic) NSString* _Nonnull type;
@end

@interface GonetFileDirDownloadTask : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) GonetDirDownloader* _Nullable f;
// skipped field FileDirDownloadTask.Ctx with unsupported type: context.Context

@end

/**
 * FileDownloadInfo 下载详情
 */
@interface GonetFileDownloadInfo : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long id_;
@property (nonatomic) long userId;
@property (nonatomic) long areaId;
@property (nonatomic) long pid;
@property (nonatomic) NSString* _Nonnull type;
@property (nonatomic) NSString* _Nonnull url;
@property (nonatomic) int64_t size;
@property (nonatomic) NSString* _Nonnull name;
@property (nonatomic) int64_t downloaded;
@property (nonatomic) int64_t speeds;
@property (nonatomic) long status;
@property (nonatomic) int64_t createTime;
@property (nonatomic) int64_t updateTime;
@property (nonatomic) NSString* _Nonnull pwd;
@property (nonatomic) NSString* _Nonnull threadInfo;
@end

@interface GonetFileDownloadTask : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) GonetFileDownloader* _Nullable f;
// skipped field FileDownloadTask.Ctx with unsupported type: context.Context

@end

/**
 * FileDownloader 下载器
 */
@interface GonetFileDownloader : NSObject <goSeqRefInterface, GonetWorker> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewFileDownloader 创建新的文件下载器,url下载连接，path存放地址， header自定义header
 */
- (nullable instancetype)init:(NSString* _Nullable)url path:(NSString* _Nullable)path headerStr:(NSString* _Nullable)headerStr pwd:(NSString* _Nullable)pwd pid:(long)pid userId:(long)userId areaId:(long)areaId;
@property (nonatomic) GonetFileDownloadInfo* _Nullable fileDownloadInfo;
@property (nonatomic) long downloadID;
@property (nonatomic) NSString* _Nonnull path;
// skipped field FileDownloader.File with unsupported type: *os.File

// skipped field FileDownloader.BlockList with unsupported type: []gomobile-download-upload/gonet.Block

// skipped field FileDownloader.Header with unsupported type: map[string]string

- (NSString* _Nonnull)getDownloadList;
/**
 * OnDelete 删除文件
 */
- (void)onDelete;
/**
 * OnFail 失败事件
 */
- (void)onFail;
/**
 * OnFinish 任务完成时触发的事件
 */
- (void)onFinish;
/**
 * OnPause 任务暂停时触发的事件
 */
- (void)onPause;
/**
 * OnQuit 退出app
 */
- (void)onQuit;
// skipped method FileDownloader.OnStart with unsupported parameter or return types

// skipped method FileDownloader.Run with unsupported parameter or return types

@end

/**
 * FileUploadInfo 上传详情
 */
@interface GonetFileUploadInfo : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long areaId;
@property (nonatomic) long userId;
@property (nonatomic) long id_;
@property (nonatomic) NSString* _Nonnull url;
@property (nonatomic) int64_t size;
@property (nonatomic) NSString* _Nonnull name;
@property (nonatomic) int64_t uploaded;
@property (nonatomic) int64_t speeds;
@property (nonatomic) long status;
@property (nonatomic) NSString* _Nonnull hash;
@property (nonatomic) int64_t createTime;
@property (nonatomic) int64_t updateTime;
@property (nonatomic) NSString* _Nonnull tmpName;
@property (nonatomic) NSString* _Nonnull pwd;
@property (nonatomic) NSString* _Nonnull threadInfo;
@end

/**
 * FileUploader 上传器
 */
@interface GonetFileUploader : NSObject <goSeqRefInterface, GonetWorker> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewFileUploader new一个文件上传器
url上传地址|dbPath数据库文件存放目录|filePath文件路径|fileName文件名|headerStr header头
 */
- (nullable instancetype)init:(NSString* _Nullable)url dbPath:(NSString* _Nullable)dbPath filePath:(NSString* _Nullable)filePath fileName:(NSString* _Nullable)fileName headerStr:(NSString* _Nullable)headerStr pwd:(NSString* _Nullable)pwd userId:(long)userId areaId:(long)areaId;
@property (nonatomic) GonetFileUploadInfo* _Nullable fileUploadInfo;
@property (nonatomic) long uploadId;
@property (nonatomic) NSString* _Nonnull filePath;
@property (nonatomic) NSString* _Nonnull path;
// skipped field FileUploader.File with unsupported type: *os.File

// skipped field FileUploader.BlockList with unsupported type: []gomobile-download-upload/gonet.Block

// skipped field FileUploader.Header with unsupported type: map[string]string

/**
 * CreateTmpFile 生成临时文件
 */
- (BOOL)createTmpFile:(NSError* _Nullable* _Nullable)error;
/**
 * OnDelete 删除下载任务
 */
- (void)onDelete;
/**
 * OnFail 失败事件
 */
- (void)onFail;
/**
 * OnFinish 任务完成时触发的事件
 */
- (void)onFinish;
/**
 * OnPause 任务暂停时触发的事件
 */
- (void)onPause;
/**
 * OnQuit 退出
 */
- (void)onQuit;
// skipped method FileUploader.OnStart with unsupported parameter or return types

/**
 * RequestMerge 发起一个合并请求
 */
- (BOOL)requestMerge:(NSError* _Nullable* _Nullable)error;
// skipped method FileUploader.Run with unsupported parameter or return types

// skipped method FileUploader.UploadBlock with unsupported parameter or return types

@end

@interface GonetResourceList : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long type;
@property (nonatomic) NSString* _Nonnull path;
@property (nonatomic) int64_t size;
@end

/**
 * ResourcesResp 请求目录详情，返回结构体
 */
@interface GonetResourcesResp : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long status;
@property (nonatomic) NSString* _Nonnull reason;
// skipped field ResourcesResp.Data with unsupported type: struct{List []gomobile-download-upload/gonet.ResourceList}

@end

@interface GonetTask : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field Task.FileTask with unsupported type: chan gomobile-download-upload/gonet.FileDownloadTask

// skipped field Task.FileDirTask with unsupported type: chan gomobile-download-upload/gonet.FileDirDownloadTask

// skipped method Task.GetFileDirDownloadTask with unsupported parameter or return types

// skipped method Task.GetFileDownloadTask with unsupported parameter or return types

// skipped method Task.SetFileDirDownloadTask with unsupported parameter or return types

// skipped method Task.SetFileDownloadTask with unsupported parameter or return types

@end

@interface GonetUploadManager : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(NSString* _Nullable)host dbPath:(NSString* _Nullable)dbPath headerStr:(NSString* _Nullable)headerStr;
// skipped field UploadManager.Workers with unsupported type: map[int]gomobile-download-upload/gonet.Worker

// skipped field UploadManager.Cancels with unsupported type: map[int]context.CancelFunc

@property (nonatomic) NSString* _Nonnull host;
@property (nonatomic) NSString* _Nonnull dbPath;
@property (nonatomic) NSString* _Nonnull headerStr;
- (void)changeHost:(NSString* _Nullable)host;
/**
 * CreateFileUploader 创建文件上传对象
 */
- (void)createFileUploader:(NSString* _Nullable)url filePath:(NSString* _Nullable)filePath fileName:(NSString* _Nullable)fileName headerStr:(NSString* _Nullable)headerStr pwd:(NSString* _Nullable)pwd userId:(long)userId areaId:(long)areaId;
- (void)delete:(long)id_;
/**
 * NetworkNil 网速设置为0，全部设置失败
 */
- (void)networkNil;
- (void)quitAPP;
/**
 * Run 开始下载任务，只能有2个任务
 */
- (void)run:(NSString* _Nullable)headerStr;
/**
 * Start 启动某个项目
 */
- (void)start:(long)id_;
/**
 * Stop 暂停某个项目
 */
- (void)stop:(long)id_;
@end

@interface GonetUploadTask : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) GonetFileUploader* _Nullable f;
// skipped field UploadTask.Ctx with unsupported type: context.Context

@end

/**
 * UploadWaitChanStruct 上传任务结构体
 */
@interface GonetUploadWaitChanStruct : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long id_;
@end

FOUNDATION_EXPORT const int64_t GonetFail;
FOUNDATION_EXPORT const int64_t GonetFinish;
FOUNDATION_EXPORT const int64_t GonetGenerating;
FOUNDATION_EXPORT const int64_t GonetOnGoing;
FOUNDATION_EXPORT const int64_t GonetStop;
FOUNDATION_EXPORT const int64_t GonetWaiting;

@interface Gonet : NSObject
/**
 * CacheSize 缓冲区大小
 */
+ (long) cacheSize;
+ (void) setCacheSize:(long)v;

+ (int64_t) chunkDownloadSize;
+ (void) setChunkDownloadSize:(int64_t)v;

+ (int64_t) chunkSize;
+ (void) setChunkSize:(int64_t)v;

// skipped variable DownloadChannelLock with unsupported type: sync.Mutex

// skipped variable DownloadStatusMap with unsupported type: map[int]int

// skipped variable DownloadTaskChan with unsupported type: gomobile-download-upload/gonet.Task

// skipped variable DownloadWaitChan with unsupported type: chan gomobile-download-upload/gonet.DownloadWaitChanStruct

+ (NSString* _Nonnull) host;
+ (void) setHost:(NSString* _Nonnull)v;

// skipped variable UploadChannelLock with unsupported type: sync.Mutex

// skipped variable UploadStatusMap with unsupported type: map[int]int

// skipped variable UploadTaskChan with unsupported type: chan gomobile-download-upload/gonet.UploadTask

// skipped variable UploadWaitChan with unsupported type: chan gomobile-download-upload/gonet.UploadWaitChanStruct

@end

FOUNDATION_EXPORT void GonetCreateDownloadTask(long downloaderId, GonetDownloadManager* _Nullable fileDownloadManager, NSString* _Nullable file, NSString* _Nullable headerStr);

// skipped function CreateUploadTask with unsupported parameter or return types


/**
 * DeletePathLastStr 删除路径字符中，最后一个元素
 */
FOUNDATION_EXPORT NSString* _Nonnull GonetDeletePathLastStr(NSString* _Nullable path);

// skipped function ExecuteTask with unsupported parameter or return types


// skipped function ExecuteUploadTask with unsupported parameter or return types


// skipped function GetContent with unsupported parameter or return types


// skipped function GetDB with unsupported parameter or return types


/**
 * GetDirDownloaderById 根据ID获取文件夹下载器
 */
FOUNDATION_EXPORT GonetDirDownloader* _Nullable GonetGetDirDownloaderById(long id_, NSString* _Nullable path, NSString* _Nullable headerStr);

/**
 * GetDirFiles 请求api地址获取目录下的所有文件
 */
FOUNDATION_EXPORT GonetResourcesResp* _Nullable GonetGetDirFiles(NSString* _Nullable api, NSString* _Nullable headerStr);

/**
 * GetDownloadList 获取下载列表
 */
FOUNDATION_EXPORT NSString* _Nonnull GonetGetDownloadList(NSString* _Nullable path, NSString* _Nullable fileType, long pId, long userId, long areaId);

/**
 * GetFileDownloaderById 根据ID获取回文件下载器
 */
FOUNDATION_EXPORT GonetFileDownloader* _Nullable GonetGetFileDownloaderById(long id_, NSString* _Nullable path, NSString* _Nullable headerStr);

/**
 * GetFileName 从下载路径中获取保存的文件名称，savePath为本地保存路径，如果文件已存在，会自动重命名
 */
FOUNDATION_EXPORT NSString* _Nonnull GonetGetFileName(NSString* _Nullable url, NSString* _Nullable savePath);

// skipped function GetFileSize with unsupported parameter or return types


/**
 * GetFileUploader url上传地址|dbPath数据库文件存放目录|filePath文件路径|headerStr header头
 */
FOUNDATION_EXPORT GonetFileUploader* _Nullable GonetGetFileUploader(NSString* _Nullable url, NSString* _Nullable dbPath, NSString* _Nullable filePath, NSString* _Nullable fileName, NSString* _Nullable headerStr, NSString* _Nullable pwd, long userId, long areaId);

// skipped function GetHash256Str with unsupported parameter or return types


// skipped function GetHeaderMap with unsupported parameter or return types


/**
 * GetLastStrByPath 在路径字符中，获取最后一个元素（如"/a/b/c", 获取c）
 */
FOUNDATION_EXPORT NSString* _Nonnull GonetGetLastStrByPath(NSString* _Nullable path);

/**
 * GetNewDirName 判断dirPath是否已存在，如果不存在，则返回。存在则需要重新命名
path目录路径，dirPath目录名称
 */
FOUNDATION_EXPORT NSString* _Nonnull GonetGetNewDirName(NSString* _Nullable path, NSString* _Nullable dirName);

/**
 * GetOnGoingTaskNum 输出任务数量
 */
FOUNDATION_EXPORT NSString* _Nonnull GonetGetOnGoingTaskNum(NSString* _Nullable path, long userId, long areaId);

/**
 * GetUploadList 获取上传列表
 */
FOUNDATION_EXPORT NSString* _Nonnull GonetGetUploadList(NSString* _Nullable path, long userId, long areaId);

/**
 * GetUploaderById 根据ID获取回上传器
 */
FOUNDATION_EXPORT GonetFileUploader* _Nullable GonetGetUploaderById(long id_, NSString* _Nullable path, NSString* _Nullable headerStr);

FOUNDATION_EXPORT GonetDirDownloader* _Nullable GonetNewDirDownloader(NSString* _Nullable findApi, NSString* _Nullable downloadApi, NSString* _Nullable downloadPath, NSString* _Nullable path, NSString* _Nullable headerStr, NSString* _Nullable pwd, long userId, long areaId, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT GonetDownloadManager* _Nullable GonetNewDownloadManager(NSString* _Nullable host, NSString* _Nullable dbPath, NSString* _Nullable headerStr);

/**
 * NewFileDownloader 创建新的文件下载器,url下载连接，path存放地址， header自定义header
 */
FOUNDATION_EXPORT GonetFileDownloader* _Nullable GonetNewFileDownloader(NSString* _Nullable url, NSString* _Nullable path, NSString* _Nullable headerStr, NSString* _Nullable pwd, long pid, long userId, long areaId, NSError* _Nullable* _Nullable error);

/**
 * NewFileUploader new一个文件上传器
url上传地址|dbPath数据库文件存放目录|filePath文件路径|fileName文件名|headerStr header头
 */
FOUNDATION_EXPORT GonetFileUploader* _Nullable GonetNewFileUploader(NSString* _Nullable url, NSString* _Nullable dbPath, NSString* _Nullable filePath, NSString* _Nullable fileName, NSString* _Nullable headerStr, NSString* _Nullable pwd, long userId, long areaId, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT GonetUploadManager* _Nullable GonetNewUploadManager(NSString* _Nullable host, NSString* _Nullable dbPath, NSString* _Nullable headerStr);

// skipped function PostFile with unsupported parameter or return types


FOUNDATION_EXPORT void GonetQuitTask(GonetDownloadManager* _Nullable fileDownloadManager, long key, NSString* _Nullable operation);

FOUNDATION_EXPORT void GonetQuitUploadTask(GonetUploadManager* _Nullable manager, long key, NSString* _Nullable operation);

/**
 * SetDbPath 数据库文件路径
 */
FOUNDATION_EXPORT void GonetSetDbPath(NSString* _Nullable path);

@class GonetCallback;

@class GonetDownloadCallBack;

@class GonetUploadCallBack;

@class GonetWorker;

@interface GonetCallback : NSObject <goSeqRefInterface, GonetCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)sendResult:(NSString* _Nullable)json;
@end

@interface GonetDownloadCallBack : NSObject <goSeqRefInterface, GonetDownloadCallBack> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onFinish:(NSString* _Nullable)p0;
- (void)onStart:(NSString* _Nullable)p0;
- (void)sendDownloadResult:(NSString* _Nullable)p0;
@end

@interface GonetUploadCallBack : NSObject <goSeqRefInterface, GonetUploadCallBack> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onFinish:(NSString* _Nullable)p0;
- (void)onStart:(NSString* _Nullable)p0;
- (void)sendUploadResult:(NSString* _Nullable)p0;
@end

@interface GonetWorker : NSObject <goSeqRefInterface, GonetWorker> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onDelete;
- (void)onFail;
- (void)onFinish;
- (void)onPause;
- (void)onQuit;
// skipped method Worker.OnStart with unsupported parameter or return types

@end

#endif
