
// Objective-C API for talking to the following Go packages
//
//	gomobile-download-upload/gonet
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Gonet_FRAMEWORK_H__
#define __Gonet_FRAMEWORK_H__

#include "Gonet.objc.h"
#include "Universe.objc.h"

#endif
